version: "3"

services:
  hive-metastore-db:
    image: ${MYSQL_IMAGE}
    hostname: metastore-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=hive_metastore
    tty: true

  hadoop:
    build:
      context: .
      dockerfile: hadoop/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: 3.3.6
        AUTHENTICATION_TYPE: noauth
    hostname: hadoop-server
    tty: true

  hive:
    build:
      context: .
      dockerfile: hive/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        HIVE_VERSION: ${HIVE_VERSION}
        AUTHENTICATION_TYPE: noauth
    hostname: hive-server
    depends_on:
      - hive-metastore-db
      - hadoop
    environment:
      SERVICE_DEPENDENCIES: "metastore-db:3306 hadoop-server:55555"
    tty: true

  kerberos:
    build:
      context: .
      dockerfile: kerberos/Dockerfile
    ports:
      - 749:749
      - 750:750
      - 88:88  
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    hostname: kerberos-server
    tty: true

  kerberized-hadoop:
    build:
      context: .
      dockerfile: hadoop/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        AUTHENTICATION_TYPE: kerberos
    ports:
      - 9000:9000
      - 9864:9864
      - 9865:9865
      - 9866:9866
      - 9867:9867
      - 9868:9868
      - 9869:9869
      - 9870:9870
      - 9871:9871
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    hostname: hadoop-server
    environment:
      SERVICE_DEPENDENCIES: "kerberos-server:749"
    depends_on:
      - kerberos
    tty: true

  kerberized-hive:
    build:
      context: .
      dockerfile: hive/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        HIVE_VERSION: ${HIVE_VERSION}
        AUTHENTICATION_TYPE: kerberos
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    hostname: hive-server
    depends_on:
      - hive-metastore-db
      - kerberos
      - kerberized-hadoop
    environment:
      SERVICE_DEPENDENCIES: "metastore-db:3306 kerberos-server:749 hadoop-server:55555"
    tty: true
